# config/meta.yml

meta_product_name: "Media Partner"
meta_title: "Media Partner - Analize"
meta_description: "Analize in real time"
meta_image: "Media-Partner.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards